name: Flask CI Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
          python-version: "3.10"
    - name: Install dependencies
      run: |
          pip install -r requirements.txt
    - name: Run tests
      run: |
          python -m pytest tests/
    - name: Build Docker image
      run: docker build -t cicd_learn .
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Tag Docker image
      run: docker tag cicd_learn ${{ secrets.DOCKER_USERNAME }}/cicd_learn:latest
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd_learn:latest